// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastLocalTransactionSubmit(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FetchWalletBalanceQuery(arg1:string):Promise<number>;

export function GetLocalNodeTelemetry():Promise<string>;
