// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastLocalTransactionSubmit(arg1, arg2, arg3) {
  return window['go']['main']['App']['BroadcastLocalTransactionSubmit'](arg1, arg2, arg3);
}

export function FetchWalletBalanceQuery(arg1) {
  return window['go']['main']['App']['FetchWalletBalanceQuery'](arg1);
}

export function GetLocalNodeTelemetry() {
  return window['go']['main']['App']['GetLocalNodeTelemetry']();
}
